### PR TITLE
GCNV-86 eggd annotate excluded regions v1.0.1

### PR DESCRIPTION
**Pull request by Aisha-D**
- Make the coordinates of the output file one-based and a tsv
- Update read me with the input file types
- Small python fixes
- Example job: https://platform.dnanexus.com/projects/GJb7kB84f2y67X2f200XpfvZ/monitor/job/GJbJKvQ4f2yFG55gJ685f2P0

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)

### CODE REVIEW

**Review by sophie22 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Aisha-D)

___
*[`dxapp.json` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQmjXvCEES6Y5w1nTY:-NGQmjXvCEES6Y5w1nTZ:bm9wcbf) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/dxapp.json#L5)):*
> ```JSON
>   "title": "eggd_annotate_excluded_regions",
>   "summary": "Annotates and filters excluded bed file for CNV reports",
>   "dxapi": "1.0.1",
> ```

dxapi version to my understanding should change, it is not directly linked to the version of the app
___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQn0-oCLmnMiYpT_cK:-NGQn0-oCLmnMiYpT_cL:bqkzf9t) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/README.md#L8)):*
> ```Markdown
> 
> ## What are the inputs?
> - Excluded regions file (zero-based))
> ```

there are 2 closing brackets
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQn5OE8LkODlQd9z6Q:-NGQn5OE8LkODlQd9z6R:bhdr05g) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/README.md#L15)):*
> ```Markdown
> 
> ## What are the outputs?
> - Annotated excluded region filtered for panel regions (one-based)
> ```

I wonder if using numbers, like 1-based, would be more apparent, happy either way
___
*[`src/eggd_annotate_excluded_regions.sh` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQoO1u9AijuBEbvGrr:-NGQoO1v53i6ZfmnjWVG:bozbn9a) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/src/eggd_annotate_excluded_regions.sh#L66)):*
> ```Shell
>     echo "--------------Converting bed to tsv -----------------"
>     cd /home/dnanexus/out/annotated_excluded_file/
>     linecount=$(wc -l $out_file  | cut -d " " -f 1)
> ```

is this the best way to check whether a file is empty?

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: all files reviewed, 5 unresolved discussions (waiting on @Aisha-D and @sophie22)

___
*[`dxapp.json` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQmjXvCEES6Y5w1nTY:-NGRZEKQ2mSHkgvAsv4O:b7u03hh) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/dxapp.json#L5)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

dxapi version to my understanding should change, it is not directly linked to the version of the app
</blockquote></details>

Correct
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQn5OE8LkODlQd9z6Q:-NGRZOxHD8YJhwZB7Dfg:blq01jm) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/README.md#L15)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

I wonder if using numbers, like 1-based, would be more apparent, happy either way
</blockquote></details>

Agree, it's not critical, but 0-based and 1-based is the more common way to describe these.
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 132 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGRlcFxBTQfo-CKAfE8:-NGRlcFxBTQfo-CKAfE9:b-f57mdk) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/resources/home/dnanexus/annotate_excluded_panel.py#L132)):*
> ```Python
>                                         "HGNC_ID", "Transcript", "Exon"]
>     # Calculate length of annotated excluded region
>     Length = exc_panel_transcript_subset.loc[:, 'End'] - exc_panel_transcript_subset.loc[:, 'Start']
> ```

lowercase `L` please, since `Length` is not a Class



_Code quote:_
```Python
L
```
___
*[`src/eggd_annotate_excluded_regions.sh` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQoO1u9AijuBEbvGrr:-NGRduua1pfQ1vT0asix:b-8m66df) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/src/eggd_annotate_excluded_regions.sh#L66)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

is this the best way to check whether a file is empty?
</blockquote></details>

https://stackoverflow.com/a/9964890

**Review by sophie22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: all files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[`dxapp.json` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGRo6gABWXqI8MWNu9b:-NGRo6gABWXqI8MWNu9c:b10adob) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/dxapp.json#L71)):*
> ```JSON
>         "*.tsv"
>       ],
>       "help": "Bed file with excluded regions filtered to panels and annotated"
> ```

if you specify above that the output file is a tsv please also update the help text
___
*[`src/eggd_annotate_excluded_regions.sh` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQoO1u9AijuBEbvGrr:-NGRoUrU7PT1xFPhH0JY:bpc2fyd) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/src/eggd_annotate_excluded_regions.sh#L66)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

https://stackoverflow.com/a/9964890
</blockquote></details>

following discussion with Aisha, I now understand that this file must exist and must at least have the appropriate header row. Therefore it will never be empty and current way of checking whether there are content lines beyond the header is appropriate

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: all files reviewed, 6 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[`dxapp.json` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQmjXvCEES6Y5w1nTY:-NGSE38a5KmmSawKw0ya:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/dxapp.json#L5)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Correct
</blockquote></details>

Done.
___
*[`dxapp.json` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGRo6gABWXqI8MWNu9b:-NGSE9C8DsQwKedss9ww:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/dxapp.json#L71)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

if you specify above that the output file is a tsv please also update the help text
</blockquote></details>

Done.
___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQn0-oCLmnMiYpT_cK:-NGSEAwS9AajgWgbqGuj:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/README.md#L8)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

there are 2 closing brackets
</blockquote></details>

Done.
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQn5OE8LkODlQd9z6Q:-NGSEPE92oBKSmjZs83C:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/README.md#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Agree, it's not critical, but 0-based and 1-based is the more common way to describe these.
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 132 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGRlcFxBTQfo-CKAfE8:-NGSEVzg-0S9ViqT1t0Q:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/resources/home/dnanexus/annotate_excluded_panel.py#L132)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

lowercase `L` please, since `Length` is not a Class
</blockquote></details>

Done.
___
*[`src/eggd_annotate_excluded_regions.sh` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGQoO1u9AijuBEbvGrr:-NGSEZsCEbE-vjbA4h4p:b-vcktc4) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e1649f040b0cf7db7c63a1ddfbcbb63241da4692/src/eggd_annotate_excluded_regions.sh#L66)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

following discussion with Aisha, I now understand that this file must exist and must at least have the appropriate header row. Therefore it will never be empty and current way of checking whether there are content lines beyond the header is appropriate
</blockquote></details>

agree with above. Also amended to check header is present and to skip adding 1bp to the header of the second column

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: all files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @sophie22)

___
*[`src/eggd_annotate_excluded_regions.sh` line 72 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGSGEji5vUxi9SDlmPK:-NGSGEji5vUxi9SDlmPL:b-1hhd4e) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/0c1963b539fb4a7a6f8e14bf2c34ed85ac3b55d7/src/eggd_annotate_excluded_regions.sh#L72)):*
> ```Shell
>         header=$(grep ^"Chrom" $out_file)
>         if [ "$header" ]; then
>             # get everything from the second header as the first header is
> ```

Should this be:
```
get everything from the second line onwards, as the first line is
```



_Code quote:_
```Shell
get everything from the second header as the first header is
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: all files reviewed, 6 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[`src/eggd_annotate_excluded_regions.sh` line 72 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5#-NGSGEji5vUxi9SDlmPK:-NGSHRcV60lNTzse6Lm6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/0c1963b539fb4a7a6f8e14bf2c34ed85ac3b55d7/src/eggd_annotate_excluded_regions.sh#L72)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should this be:
```
get everything from the second line onwards, as the first line is
```
</blockquote></details>

Done.

**Review by sophie22 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
