### PR TITLE
GCNV-31 eggd annotate excluded regions v1.0.0 annotate additional regions

### PR DESCRIPTION
**Pull request by Aisha-D**
- Add another input for additional regions file which contains more annotation info that is absent from the cds files.
- Remove transcript versioning (no longer required as it will use the panel bed generated by the same cds file)

An example of the last region in the screenshots below containing a non-exon additional region and not annotated correctly with the current version of the app.
Before:
Screenshot from 2022-08-25 15-22-30

After:
Screenshot from 2022-08-26 15-14-11

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4)* status: all files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NAe3S5B00ZQuqK-IiFu:-NAe3S5B00ZQuqK-IiFv:btbdfna) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/c789336330119fb8d423606ed1a5c629660a8bd6/dxapp.json#L57)):*
> ```JSON
>       "label": "File containing chrom, start, end, *, gene/panel name.",
>       "class": "file",
>       "optional": false,
> ```

Could this be made optional, since there may not always be additional regions?

This will also require changes to the script to not append the additional regions if it isn't provided.



_Code quote:_
```JSON
optional": false
```
___
*[`src/eggd_annotate_excluded_regions.sh` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NAe3hMr8ifHVlTzqe-Y:-NAe3hMr8ifHVlTzqe-Z:b-eiq9jp) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/c789336330119fb8d423606ed1a5c629660a8bd6/src/eggd_annotate_excluded_regions.sh#L19)):*
> ```Shell
> 
>     # skip first row as its header than cat it to the end of the cds file
>     sed 1d $additional_regions_path | cat $cds_hgnc_path - > cds_exons_w_additional_regions.tsv
> ```

See other comment about making this optional.



_Code quote:_
```Shell
sed 1d $additional_regions_path | cat $cds_hgnc_path - > cds_exons_w_additional_regions.tsv
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NAe3S5B00ZQuqK-IiFu:-NAiACHsBf6z--qd4LJo:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/c789336330119fb8d423606ed1a5c629660a8bd6/dxapp.json#L57)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this be made optional, since there may not always be additional regions?

This will also require changes to the script to not append the additional regions if it isn't provided.
</blockquote></details>

Done.
___
*[`src/eggd_annotate_excluded_regions.sh` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NAe3hMr8ifHVlTzqe-Y:-NAiADUC-Q6GByj4vqTO:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/c789336330119fb8d423606ed1a5c629660a8bd6/src/eggd_annotate_excluded_regions.sh#L19)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

See other comment about making this optional.
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4)* status: all files reviewed, 5 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[`src/eggd_annotate_excluded_regions.sh` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBR6AVc7x478ZZs1YnS:-NBR6AVc7x478ZZs1YnT:b-bcwrp3) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L23)):*
> ```Shell
>         if [ "$additional_regions" ]; then
>             # skip first row as its header than cat it to the end of the cds file
>             sed 1d $additional_regions_path | cat $cds_hgnc_path - > cds_exons.tsv
> ```

Does it matter that these end up unsorted in cds_exons.tsv?



_Code quote:_
```Shell
sed 1d $additional_regions_path | cat $cds_hgnc_path - > cds_exons.tsv
```
___
*[`src/eggd_annotate_excluded_regions.sh` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBRcfT13CkuTT4MOOSt:-NBRcfT13CkuTT4MOOSu:bjcp7tl) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L38)):*
> ```Shell
> 
>         else
>             echo "Panel bed file is provided, so the gCNV excluded regions will be interested with panel bed file."
> ```

intersected



_Code quote:_
```Shell
interested
```
___
*[`src/eggd_annotate_excluded_regions.sh` line 41 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBRcn5u05MhwUKoXkqV:-NBRcn5v0Mq7l2kkxwl0:b-2eovha) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L41)):*
> ```Shell
>             # -wa will keep the a (excluded file) start and end rather than the start and end of both files
>             bedtools intersect -a $excluded_regions_path -b $panel_bed_path -wa | sort | uniq > panel_excluded.bed
>             head panel_excluded.bed
> ```

Should this be removed?



_Code quote:_
```Shell
head panel_excluded.bed
```
___
*[`src/eggd_annotate_excluded_regions.sh` line 43 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBRd0pl876MRAN25L1o:-NBRd0pmBVK8bVjLI-o5:bt1h0uw) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L43)):*
> ```Shell
>             head panel_excluded.bed
>             # some panels may not be excluded so the panel_excluded.bed so have
>             # an empty file outputted here.
> ```

Could this be described a bit more clearly?



_Code quote:_
```Shell
            # some panels may not be excluded so the panel_excluded.bed so have
            # an empty file outputted here.
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @mattgarner)

___
*[`src/eggd_annotate_excluded_regions.sh` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBR6AVc7x478ZZs1YnS:-NBRgRCE44zrPKjZn6wI:b4odpuo) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L23)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does it matter that these end up unsorted in cds_exons.tsv?
</blockquote></details>

Dont think it makes a difference as when the additional regions are provided they appear in the output file and also dont think bedtools intersect cares about order - unless order matters for bedtools intersect
___
*[`src/eggd_annotate_excluded_regions.sh` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBRcfT13CkuTT4MOOSt:-NBRhExQ58I40sQCv8T6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L38)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

intersected
</blockquote></details>

Done.
___
*[`src/eggd_annotate_excluded_regions.sh` line 41 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBRcn5u05MhwUKoXkqV:-NBRhKVe-N0QNcotSDb2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should this be removed?
</blockquote></details>

Done.
___
*[`src/eggd_annotate_excluded_regions.sh` line 43 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBRd0pl876MRAN25L1o:-NBRi2BS2ob3GcjrBTrB:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this be described a bit more clearly?
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/eggd_annotate_excluded_regions.sh` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4#-NBR6AVc7x478ZZs1YnS:-NBSDv957CQWe_3Q3EWm:b-gzomi2) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/46967a917e30477d4d325bcf73b67525be6e9cfd/src/eggd_annotate_excluded_regions.sh#L23)):*
<details><summary><i>Previously, Aisha-D (Aisha Dahir) wrote…</i></summary><blockquote>

Dont think it makes a difference as when the additional regions are provided they appear in the output file and also dont think bedtools intersect cares about order - unless order matters for bedtools intersect
</blockquote></details>

It depends
If the command contains `-sorted` then it will assume sorted input which might cause issues. Best to play is safe just in case and add a sort (sort -k1,1 -k2,2n) before writing to file
See Note in https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html for more info

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
