### PR TITLE
GCNV-31 eggd annotate excluded regions v.1.0.0

### PR DESCRIPTION
**Pull request by Aisha-D**
- First app to filter and annotate excluded regions
- recent job: https://platform.dnanexus.com/projects/GFQQyVQ4qq8j6kXG1Xkfy3G3/monitor/job/GFxkYzj4qq8g5Pz5KK0j59yq

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`dxapp.json` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b7jeO7zTzZ1P3ilV_:-N9b7jeO7zTzZ1P3ilVa:b-4kqjup) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/dxapp.json#L5)):*
> ```JSON
>   "title": "eggd_annotate_excluded_regions",
>   "summary": "Annotates and filters excluded bed file for CNV reports",
>   "dxapi": "1.0.0",
> ```

Still need a version argument which links to the app version.

"version": "1.0.0",
___
*[`dxapp.json` line 76 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b8-uE8EcvjeBGu2Hh:-N9b8-uE8EcvjeBGu2Hi:b8s1es1) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/dxapp.json#L76)):*
> ```JSON
>       },
>       {
>         "name": "python_packages",
> ```

Do you need all the packages from here? 

We can get the whl files instead and only install things you need. :) 
___
*[`README.md` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b88xm5Y11GsMXbTpS:-N9b88xm5Y11GsMXbTpT:b-uqmnjn) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/README.md#L5)):*
> ```Markdown
> ## What does this app do?
> 
> This app takes in the excluded region file generated by gCNV_call for every run to show regions that CNV calling wasn't performed in. The excluded regions file will be filtered for the panel, then annotated for the HGNC ID and exon number using the exons file.
> ```

With Symbol also, and length calculated.
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 104 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b8su9BuJ6C7C9LIqH:-N9b8su9BuJ6C7C9LIqI:b2liimy) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/resources/home/dnanexus/annotate_excluded_panel.py#L104)):*
> ```Python
>                                         "HGNC_ID", "Transcript", "Exon"]
>     # Calculate length of CNV
>     exc_panel_transcript_subset['Length'] = exc_panel_transcript_subset['End'] - exc_panel_transcript_subset['Start']
> ```

As mentioned I think Length should be (END-POS) +1 to account for the position itself.
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 121 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b9wqf3KI-zevUYMwt:-N9b9wqf3KI-zevUYMwu:b-1v4cld) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/resources/home/dnanexus/annotate_excluded_panel.py#L121)):*
> ```Python
>     df2 = df2[["Chrom", "Start", "End", "Length",
>                 "Gene_Symbol", "HGNC_ID","Transcript", "Exon"]]
>     print("df2")
> ```

Are you actually printing this? Not part of the logs from the job you linked?
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 127 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9bA8xS3FkTq1bJroGb:-N9bA8xT4gNiIF9F21CX:b-faytp9) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/resources/home/dnanexus/annotate_excluded_panel.py#L127)):*
> ```Python
>     panel_name = args.panel
>     panel_name = panel_name.split("/")[-1]
>     panel_name = panel_name.split(".bed")[0]
> ```

you could make this one line with



_Code snippet:_
```Python
panel_name=panel_name.split("/")[-1].rstrip(".bed")
```
___
*[`src/eggd_annotate_excluded_regions.sh` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9bAaUNAIEo7iumFEK6:-N9bAaUO4iD5TC8SIHHs:b-lq17hw) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/src/eggd_annotate_excluded_regions.sh#L16)):*
> ```Shell
> 
>     bedtools intersect -a $excluded_regions_path -b $panel_bed_path | sort | uniq > panel_excluded.bed
>     head panel_excluded.bed
> ```

is there a reason you use head here? or just for the logs?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @Addy81)

___
*[`dxapp.json` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b7jeO7zTzZ1P3ilV_:-N9ezeAc3LEEF6BH_JyD:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/dxapp.json#L5)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Still need a version argument which links to the app version.

"version": "1.0.0",
</blockquote></details>

Done.
___
*[`dxapp.json` line 76 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b8-uE8EcvjeBGu2Hh:-N9ezi6C7GpdYjKv-C8H:b-vd8gl3) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/dxapp.json#L76)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Do you need all the packages from here? 

We can get the whl files instead and only install things you need. :) 
</blockquote></details>

I couldn't find where we previously got the whl for the other apps developed but saw this asset used. Only some of the packages are installed in the bash script
___
*[`README.md` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b88xm5Y11GsMXbTpS:-N9ezxhz8H710v5VPDaI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/README.md#L5)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

With Symbol also, and length calculated.
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 121 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b9wqf3KI-zevUYMwt:-N9f--mq9oZ8PEeFexYm:b-ukwgsq) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/resources/home/dnanexus/annotate_excluded_panel.py#L121)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Are you actually printing this? Not part of the logs from the job you linked?
</blockquote></details>

removed - was there for testings :) 
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 127 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9bA8xS3FkTq1bJroGb:-N9f-2wlAgq6vBeCYz_E:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/resources/home/dnanexus/annotate_excluded_panel.py#L127)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

you could make this one line with
</blockquote></details>

Done.
___
*[`src/eggd_annotate_excluded_regions.sh` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9bAaUNAIEo7iumFEK6:-N9f-3f89voC6rATarmH:bmvkok8) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/src/eggd_annotate_excluded_regions.sh#L16)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

is there a reason you use head here? or just for the logs?
</blockquote></details>

thinking of leaving here for logs. Could do cat but it would be very long

**Review by Addy81 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`dxapp.json` line 76 at r1](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-N9b8-uE8EcvjeBGu2Hh:-NA537ep9qn5V3YL3wjI:byerlji) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/f753ec09f090df5f62438447168d92af678331f3/dxapp.json#L76)):*
<details><summary><i>Previously, Aisha-D (Aisha Dahir) wrote…</i></summary><blockquote>

I couldn't find where we previously got the whl for the other apps developed but saw this asset used. Only some of the packages are installed in the bash script
</blockquote></details>

Here's my notes on doing that: https://evening-sailboat-bb7.notion.site/App-making-get-whl-files-ecf10dbf216f4ddba5483d4ba839b164
If you want to keep it this way is fine, but in the future to get the most up2date versions you can do the above.
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 19 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA55D6_8uREp5-XFCV1:-NA55D6_8uREp5-XFCV2:b-i8eb9z) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/resources/home/dnanexus/annotate_excluded_panel.py#L19)):*
> ```Python
>     parser.add_argument(
>         '-e', '--excluded_panel',
>         help='Excluded file filtered to panel',
> ```

Can we change the help to 'Excluded regions file intersected with requested panel regions.
___
*[`src/eggd_annotate_excluded_regions.sh` line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA565Qs1jGZof0IoHV_:-NA565Qs1jGZof0IoHVa:bf464eu) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/src/eggd_annotate_excluded_regions.sh#L18)):*
> ```Shell
>     head panel_excluded.bed
>     # some panels may not be excluded so the panel_excluded.bed so have
>     # an empty file outputted here. How to deal with the naming system?
> ```

did you intend to leave this question here?
___
*[`src/eggd_annotate_excluded_regions.sh` line 21 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA54ELPCcYz4Zaq3L8w:-NA54ELPCcYz4Zaq3L8x:b7rbm3) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/src/eggd_annotate_excluded_regions.sh#L21)):*
> ```Shell
> 
>     if [ -s panel_excluded.bed ]; then
>         echo "Some panels are in excluded regions, annotation will be attempted."
> ```

Can we change the wording here? The whole panel won't be in the excluded regions file. 

Some panel regions overalal with the gCNV excluded regions, these will be annotated.
___
*[`src/eggd_annotate_excluded_regions.sh` line 26 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA54Wel-pPZC1hMt03n:-NA54Wel-pPZC1hMt03o:b-56jfvi) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/src/eggd_annotate_excluded_regions.sh#L26)):*
> ```Shell
>         python3 annotate_excluded_panel.py -e panel_excluded_genes.bed -p $panel_bed_path -r $excluded_regions_path -g $exons_gene_path
>     else
> 		echo "Panel is not in excluded region"
> ```

Same as above. Panel regions do not overlap with cnv calling excluded regions.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`src/eggd_annotate_excluded_regions.sh` line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA565Qs1jGZof0IoHV_:-NA59BEgB_1i3QhEW5tR:b-nvgz43) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/src/eggd_annotate_excluded_regions.sh#L18)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

did you intend to leave this question here?
</blockquote></details>

lol no
___
*[`src/eggd_annotate_excluded_regions.sh` line 21 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA54ELPCcYz4Zaq3L8w:-NA59xBI-GOVUnEkkgSt:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/src/eggd_annotate_excluded_regions.sh#L21)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Can we change the wording here? The whole panel won't be in the excluded regions file. 

Some panel regions overalal with the gCNV excluded regions, these will be annotated.
</blockquote></details>

Done.
___
*[`src/eggd_annotate_excluded_regions.sh` line 26 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA54Wel-pPZC1hMt03n:-NA59xTKCYIwd93On6HF:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/src/eggd_annotate_excluded_regions.sh#L26)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Same as above. Panel regions do not overlap with cnv calling excluded regions.
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 19 at r3](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2#-NA55D6_8uREp5-XFCV1:-NA5BPIA9RZsUMDF-gNs:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ece20cc222ce9f2b042dc3e3ca48e89c7c608b1e/resources/home/dnanexus/annotate_excluded_panel.py#L19)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Can we change the help to 'Excluded regions file intersected with requested panel regions.
</blockquote></details>

Done.

**Review by Addy81 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Addy81 and @Aisha-D)

**Review by Addy81 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
