### PR TITLE
GCNV-31 first version of applet

### PR DESCRIPTION
**Pull request by Aisha-D**
- Filters for excluded file within panel then adds HGNC IDs and exons from exons file
- example job: https://platform.dnanexus.com/projects/GFQQyVQ4qq8j6kXG1Xkfy3G3/monitor/job/GFkx0pQ4qq8xpf826Vvq1BFy

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
Sorry minor things to change.
Should the output file name be named in some form of the panel it was filtered? With a fraction of the name of the run and then filtered by panel. Like take the name of the gCNV output then suffix or prefix with the R indication. Otherwise we would have 48 files named the same :) 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-:-N9BPaCf-KRjB0lpasPr:b-x1nphh)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`dxapp.json` line 6 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9B8tfv3QEIup_VAAVY:-N9B8tfv3QEIup_VAAVZ:bpcgigm) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/dxapp.json#L6)):*
> ```JSON
>   "summary": "Annotates and filters excluded bed file for CNV reports",
>   "dxapi": "1.0.0",
>   "version": "0.0.1",
> ```

Should this be 1.0.0?

also should we still gave the github release property in?

 "properties": {
    "githubRelease": "1.0.0"
  },
___
*[`dxapp.json` line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9B9Zj1-z5JBxVJA0to:-N9B9Zj1-z5JBxVJA0tp:b-69q5dw) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/dxapp.json#L15)):*
> ```JSON
>         "*"
>       ],
>       "help": ""
> ```

Could we add help strings for all the inputs to describe them? 
Makes it easier when someone picks it up on a later date.
___
*[`dxapp.json` line 22 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9B9fxI3K3qUrjVNcQG:-N9B9fxI3K3qUrjVNcQH:b-sswpde) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/dxapp.json#L22)):*
> ```JSON
>       "optional": false,
>       "patterns": [
>         "*"
> ```

also patterns for the ones you only want those type of files.
___
*[`dxapp.json` line 70 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BAFFMBHRchcKhntlr:-N9BAFFMBHRchcKhntls:blvk8mr) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/dxapp.json#L70)):*
> ```JSON
>         "version": "1.1.0"
>       }
>     ]
> ```

Add the app specific dev and user sections to restrict use to our org:

"developers":[
    "org-emee_1"
  ],
  "authorizedUsers": [
    "org-emee_1"
___
*[`README.md` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BAX-68TuDUQOqvELd:-N9BAX-68TuDUQOqvELe:bghfyon) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/README.md#L5)):*
> ```Markdown
> ## What does this app do?
> 
> This app takes in the excluded files generated per run basis, panel bed generated per sample and the exons files. The excluded will be filtered for the panel, then annotated for the HGNC ID and exon number using the exons file.
> ```

Could we change the first sentence.

This app takes in the excluded region file generated by gCNV_call for every run to show regions that CNV calling wasn't performed in.  

Then the rest is fine. Just to show it probably only work and is tested with gCNV output.
___
*[`README.md` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BAUWEANxMbqnCt1Ex:-N9BAUWEANxMbqnCt1Ey:b-s01erj) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/README.md#L13)):*
> ```Markdown
> 
> ## What are the outputs?
> - Annoated excluded region filtered for panel regions.
> ```

typo annotated
___
*[`README.md` line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BAv_425M6JlP6NRSI:-N9BAv_425M6JlP6NRSJ:b-90tfxu) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/README.md#L16)):*
> ```Markdown
> 
> ## Where is this app applicable?
> For CNV reports.
> ```

 Currently this is only germline CNV workflow. 
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 8 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BB4cP982zfraxrcxL:-N9BB4cP982zfraxrcxM:bgbploy) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/resources/home/dnanexus/annotate_excluded_panel.py#L8)):*
> ```Python
> 
> def parse_args():
>     """Parse through arguements
> ```

typo in arguments
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BICBa759LO4azeD0B:-N9BICBa759LO4azeD0C:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/resources/home/dnanexus/annotate_excluded_panel.py#L11)):*
> ```Python
>     Returns:
>         args: Variable that you can extract relevant
>         arguements inputs needed
> ```

typo
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BP62b-LlKcxkJUb8g:-N9BP62b-LlKcxkJUb8h:bgmp48o) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/resources/home/dnanexus/annotate_excluded_panel.py#L75)):*
> ```Python
>                                     "transcript", "exon"]]
>     # rename columns
>     exc_panel_transcript_subset.columns = ["Chr", "Pos_start", "Pos_end",
> ```

Could we rename these Chrom, Start and End? to fit with bed specs and if passed on the workbook they are clearer.



_Code quote (from src/eggd_annotate_excluded_regions.sh):_
```Shell
    bedtools intersect -b $exons_file_path -a panel_exluded.bed -wa -wb > panel_excluded_genes.bed
```
___
*[`src/eggd_annotate_excluded_regions.sh` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BNYbQCCn-rEoxW_Li:-N9BNYbQCCn-rEoxW_Lj:buywptw) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/src/eggd_annotate_excluded_regions.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

# -e = exit on error; -x = output each line that is executed to log; -o pipefail = throw an error if there's an error in pipeline
set -e -x -o pipefail

Add the above line so your logs show the commands that have been run.



_Code quote (from resources/home/dnanexus/annotate_excluded_panel.py):_
```Python
    exc_panel = pd.read_csv(args.excluded_panel, sep="\t", header=None)
    panel = pd.read_csv(args.panel, sep="\t", header=None)
```

**Review by Aisha-D — COMMENTED** [review]
That's true! Forgot to about each one being the same. Would it best to do as: projectname_samplename_Rnumber?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-:-N9BRCysBoZDcjDC_kpA:b-1739js)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`dxapp.json` line 6 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9B8tfv3QEIup_VAAVY:-N9BRq_f8mBk3JibckG3:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/dxapp.json#L6)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Should this be 1.0.0?

also should we still gave the github release property in?

 "properties": {
    "githubRelease": "1.0.0"
  },
</blockquote></details>

Done.
___
*[`dxapp.json` line 22 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9B9fxI3K3qUrjVNcQG:-N9BS5Z-8-w0ByVQFg3V:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/dxapp.json#L22)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

also patterns for the ones you only want those type of files.
</blockquote></details>

Done.

**Review by Addy81 — COMMENTED** [review]
We don't need the sample name. So run and R number or run and full panel name? It won't always be R numbers if they have any single gene requests.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-:-N9BSg2F1FI043W3nR2G:btw5nvq)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @Addy81 and @Aisha-D)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`dxapp.json` line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9B9Zj1-z5JBxVJA0to:-N9BVsFA8Xrj7glBzr51:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/dxapp.json#L15)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could we add help strings for all the inputs to describe them? 
Makes it easier when someone picks it up on a later date.
</blockquote></details>

Done.
___
*[`README.md` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BAX-68TuDUQOqvELd:-N9BWGQIA6y6tpRWH4Zv:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/README.md#L5)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could we change the first sentence.

This app takes in the excluded region file generated by gCNV_call for every run to show regions that CNV calling wasn't performed in.  

Then the rest is fine. Just to show it probably only work and is tested with gCNV output.
</blockquote></details>

Done.
___
*[`README.md` line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BAv_425M6JlP6NRSI:-N9BWFAN4wnirshxEy9S:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/README.md#L16)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

 Currently this is only germline CNV workflow. 
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BICBa759LO4azeD0B:-N9BWXgw65qJzGarCuyu:b8g7re6) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/resources/home/dnanexus/annotate_excluded_panel.py#L11)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

typo
</blockquote></details>

vowels typos will never leave me alone.
___
*[`src/eggd_annotate_excluded_regions.sh` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BNYbQCCn-rEoxW_Li:-N9BX83e-YpRPfgu9Jz-:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/src/eggd_annotate_excluded_regions.sh#L2)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

# -e = exit on error; -x = output each line that is executed to log; -o pipefail = throw an error if there's an error in pipeline
set -e -x -o pipefail

Add the above line so your logs show the commands that have been run.
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
Heres the job with the latest changes: https://platform.dnanexus.com/projects/GFQQyVQ4qq8j6kXG1Xkfy3G3/monitor/job/GFpP9v04qq8j49P24YfQ8YFX

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-:-N9Brs_mCoe5Jwvg_Z2M:b8wzll9)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @Addy81 and @Aisha-D)

___
*[`README.md` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BAUWEANxMbqnCt1Ex:-N9BsH772Si_RGf06Zti:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/README.md#L13)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

typo annotated
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/annotate_excluded_panel.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/eggd_annotate_excluded_regions/1#-N9BP62b-LlKcxkJUb8g:-N9BsCJhC2AOHOGNTREN:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/e7a2190e283c2a6f8e604c5ff76c03c9da75a5d8/resources/home/dnanexus/annotate_excluded_panel.py#L75)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could we rename these Chrom, Start and End? to fit with bed specs and if passed on the workbook they are clearer.
</blockquote></details>

Done.

**Comment by Aisha-D** [comment]
the whole app has been redesigned and will require more changes. Another PR will be opened

**Pull request closed without merging**
